---
- name: List Jenkins Plugins and Versions
  hosts: localhost
  gather_facts: false
  vars:
    jenkins_url: "http://18.234.101.245:8080"
    jenkins_username: "nrk"
    jenkins_password: "nrk"

  tasks:
    - name: Download Jenkins CLI jar
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: /tmp/jenkins-cli.jar

    - name: List plugins and versions
      shell: java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins
      register: plugins_output

    - name: Parse plugin names and versions
      set_fact:
        plugin_info: "{{ plugins_output.stdout_lines[1:] | map('regex_replace', '^([^ ]+)[^0-9]+([0-9].*)$', '\\1:\\2') | list }}"

    - name: Display plugin names and versions
      debug:
        msg: "{{ item }}"
      loop: "{{ plugin_info }}"

    # - name: Check for plugin updates
    #   command: java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins --filter hasUpdate=true --short
    #   register: plugins_updates
    #   changed_when: false
    #   ignore_errors: true

    - name: Check for plugin updates
      set_fact:
        plugins_with_updates: "{{ plugin_info | json_query('[?contains(@, \'(update available)\')]') }}"

    # - name: Upgrade plugins
    #   command: java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' install-plugin '{{ item.split(':')[0] }}' --deploy
    #   loop: "{{ plugins_with_updates }}"
    #   when: plugins_with_updates | length > 0

    # - name: Upgrade plugins
    #   command: java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' install-plugin '{{ item.split(':')[0] }}' --deploy
    #   loop: "{{ plugins_updates.stdout_lines }}"
    #   when: plugins_updates.stdout_lines | length > 0

#    - name: Upgrade Jenkins plugins
#      command: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' install-plugin '{{ item }}' -deploy"
#      loop: "{{ installed_plugins.stdout_lines }}"
#      changed_when: true

#    - name: Get installed plugins (after upgrade)
#      shell: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins"
#      register: installed_plugins_after
