---
- name: Upgrade Jenkins Plugins
  hosts: localhost
  # become: true

  vars:
    jenkins_url: "http://18.234.101.245:8080"
    jenkins_username: "nrk"
    jenkins_password: "nrk"

  tasks:
    - name: Download Jenkins CLI jar
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: /tmp/jenkins-cli.jar

    - name: Get installed plugins
      command: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins"
      register: installed_plugins

    - name: Create a Lists with Numbers, Strings and Dictionary
      set_fact:
        list_installed_plugins: "{{ installed_plugins }}"

    - name: Show all the hosts in the current play
      ansible.builtin.debug:
       msg: 
         - "{{ item }}"
        # - "{{ item.name }}"
        # - "{{ item.version }}"
      loop: "{{ list_installed_plugins }}"

#    - name: Upgrade Jenkins plugins
#      command: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' install-plugin '{{ item }}' -deploy"
#      loop: "{{ installed_plugins.stdout_lines }}"
#      changed_when: true

#    - name: Get installed plugins (after upgrade)
#      shell: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins"
#      register: installed_plugins_after
