---
- name: List Jenkins Plugins and Versions
  hosts: localhost
  gather_facts: false
  vars:
    jenkins_url: "http://18.234.101.245:8080"
    jenkins_username: "nrk"
    jenkins_password: "nrk"

  tasks:
    - name: Download Jenkins CLI jar
      get_url:
        url: "{{ jenkins_url }}/jnlpJars/jenkins-cli.jar"
        dest: /tmp/jenkins-cli.jar

    - name: List plugins and versions
      shell: java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins
      register: plugins_output

    - name: Parse plugin names and versions
      set_fact:
        plugin_info: "{{ plugins_output.stdout_lines[1:] | map('regex_replace', '^([^ ]+)[^0-9]+([0-9].*)$', '\\1:\\2') | list }}"

    - name: Display plugin names and versions
      debug:
        msg: "{{ item }}"
      loop: "{{ plugin_info }}"

    - name: Upgrade Jenkins plugins
      command: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' install-plugin '{{ item }}' -deploy"
      loop: "{{ plugin_info.stdout_lines }}"
      changed_when: true
    
    - name: Get installed plugins (after upgrade)
       shell: "java -jar /tmp/jenkins-cli.jar -s '{{ jenkins_url }}' -auth '{{ jenkins_username }}:{{ jenkins_password }}' list-plugins"
       register: installed_plugins_after
    
    - name: Display plugin names and versions after upgradation
        debug:
          msg: "{{ item }}"
        loop: "{{ installed_plugins_after }}"
